---
title: "hw5"
author: "Vasilisa Dyomina"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ca)
```

### 5.1
```{r}
chairs <- read_csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/VaDyomina/hw5_CA_MCA/hw5_chairs.csv')
MCA <- MASS::mca(chairs[,-c(1,2,3)])
chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names))+
  theme_bw()+
  scale_x_continuous(limits = c(-0.015, 0.02))
```

### 5.2
```{r}
```

### 5.3
```{r}
colreg <- read_csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/VaDyomina/hw5_CA_MCA/hw5_colreg.csv')
ca <- ca(colreg[, -5])

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)

colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>%
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colreg_row, color = "red")+
  theme_bw()
```

### 5.4
```{r}
```